# Generated by Django 5.0.6 on 2024-07-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0004_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this usser.', related_name='customuser_set', related_query_name='customuser', to='auth.permission'),
        ),
    ]
